#!/usr/bin/python3
def raise_exception_msg(message=""):
    # raise a name exception with the given message
    raise NameError(message)
